name: Build and Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: clean-gyp
        run: rm -rf ~/.node-gyp ~/.cache/node-gyp
      - name: linux-dependencies
        run: apt-get install -y \
          build-essential \
          g++ \
          libx11-dev \
          libxkbfile-dev \
          libsecret-1-dev \
          libkrb5-dev \
          python-is-python3
      - name: build
        run: yarn build
      - name: publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
